# Generated by Django 4.0.2 on 2022-03-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.CharField(help_text='Without proceeding or appending slashes', max_length=200),
        ),
    ]
