# Generated by Django 4.0.2 on 2022-03-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_unique_together_remove_category_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Markdown allowed'),
        ),
    ]
