# Generated by Django 3.2.3 on 2021-08-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='all_vegan',
            field=models.BooleanField(default=False),
        ),
    ]
