# Generated by Django 4.0.2 on 2022-02-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_restaurant_all_vegan'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
