# Generated by Django 3.2.3 on 2021-06-02 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20210602_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='linkcategory',
            options={'verbose_name_plural': 'link categories'},
        ),
        migrations.AlterModelOptions(
            name='vegancompany',
            options={'verbose_name_plural': 'vegan companies'},
        ),
    ]
