# Generated by Django 3.2.3 on 2021-06-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_vegancompany_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegancompany',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
